/*++

Module Name:

    device.c - Device handling events for example driver.

Abstract:

   This file contains the device entry points and callbacks.

Environment:

    Kernel-mode Driver Framework

--*/

#include "driver.h"
#include "device.tmh"
#include <ntstrsafe.h.>
#ifdef ALLOC_PRAGMA
#pragma alloc_text (PAGE, StudyKMDFCreateDevice)
#endif

NTSTATUS
StudyKMDFCreateDevice(
    _Inout_ PWDFDEVICE_INIT DeviceInit
    )
/*++

Routine Description:

    Worker routine called to create a device and its software resources.

Arguments:

    DeviceInit - Pointer to an opaque init structure. Memory for this
                    structure will be freed by the framework when the WdfDeviceCreate
                    succeeds. So don't access the structure after that point.

Return Value:

    NTSTATUS

--*/
{
    WDF_OBJECT_ATTRIBUTES deviceAttributes;
    PDEVICE_CONTEXT deviceContext;
    WDFDEVICE device;
    NTSTATUS status;

    PAGED_CODE();

    WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE(&deviceAttributes, DEVICE_CONTEXT);

    status = WdfDeviceCreate(&DeviceInit, &deviceAttributes, &device);

    if (NT_SUCCESS(status)) {
        //
        // Get a pointer to the device context structure that we just associated
        // with the device object. We define this structure in the device.h
        // header file. DeviceGetContext is an inline function generated by
        // using the WDF_DECLARE_CONTEXT_TYPE_WITH_NAME macro in device.h.
        // This function will do the type checking and return the device context.
        // If you pass a wrong object handle it will return NULL and assert if
        // run under framework verifier mode.
        //
        deviceContext = DeviceGetContext(device);

        //
        // Initialize the context.
        //
        deviceContext->PrivateDeviceData = 0;
        deviceContext->pWMIObject = NULL;
        RtlZeroMemory(deviceContext->wmiInstanceName,
                      sizeof(deviceContext->wmiInstanceName));
        //
        // Create a device interface so that applications can find and talk
        // to us.
        //
        status = WdfDeviceCreateDeviceInterface(
            device,
            &GUID_DEVINTERFACE_StudyKMDF,
            NULL // ReferenceString
            );

        if (NT_SUCCESS(status)) {
            //
            // Initialize the I/O Package and any Queues
            //
            status = StudyKMDFQueueInitialize(device);
        }

        GUID sampleWMIACPI = DEMO_WMIACPI_GUID;

        status = IoWMIOpenBlock(&sampleWMIACPI, WMIGUID_EXECUTE,
                                &deviceContext->pWMIObject);

        if (!NT_SUCCESS(status)) {
          KdPrintEx((DPFLTR_IHVDRIVER_ID, DPFLTR_ERROR_LEVEL,
                     "Failed, execute IoWMIOpenBlock(), return %d\n", status));
          return status;
        }

        BYTE buff[2048];
        ULONG buffSize = sizeof(buff);
        status = IoWMIQueryAllData(deviceContext->pWMIObject, &buffSize, buff);
        if (!NT_SUCCESS(status)) {
            KdPrintEx((DPFLTR_IHVDRIVER_ID, DPFLTR_ERROR_LEVEL,
                       "Failed: IoWMIQueryAllData() returned 0x%08X\n", status));
            return status;
        }

        // pick the first Instance Name, and store it
        // the demo code only pick the first instance
        WNODE_ALL_DATA *pWNode = (WNODE_ALL_DATA *)buff;
        if (pWNode->InstanceCount < 1 || pWNode->OffsetInstanceNameOffsets == 0) {
            KdPrintEx((DPFLTR_IHVDRIVER_ID, DPFLTR_ERROR_LEVEL,
                       "Unexpected WMI structure: no instance names\n"));
            return STATUS_UNSUCCESSFUL;
        }

        ULONG nameOffset = *((PULONG)(buff + pWNode->OffsetInstanceNameOffsets));
        PUCHAR pNameRaw = buff + nameOffset;

        USHORT nameLen = *((USHORT*)pNameRaw); // in bytes
        PWCHAR nameStr = (PWCHAR)(pNameRaw + sizeof(USHORT));

        // Avoid deviceContext overflow
        size_t maxCopyLen = sizeof(deviceContext->wmiInstanceName);
        if (nameLen + sizeof(WCHAR) > maxCopyLen) {
            KdPrintEx((DPFLTR_IHVDRIVER_ID, DPFLTR_ERROR_LEVEL,
                       "WMI instance name too long to fit in buffer\n"));
            return STATUS_BUFFER_OVERFLOW;
        }

        // Copy（Tips: WMI maybe without a null terminator）
        RtlZeroMemory(deviceContext->wmiInstanceName, maxCopyLen);
        RtlCopyMemory(deviceContext->wmiInstanceName, nameStr, nameLen);
        deviceContext->wmiInstanceName[nameLen / sizeof(WCHAR)] = L'\0'; // add null terminator

        KdPrintEx((DPFLTR_IHVDRIVER_ID, DPFLTR_INFO_LEVEL,
                   "WMI instance: %ws\n", deviceContext->wmiInstanceName));
    }

    return status;
}
